### ISSUE TITLE
ClassCastException: TokenBuffer cannot be cast to MongoBsonGenerator

### ISSUE THREAD

**Issue by haraldrombaut** [bguerout/jongo#257]
jackson version is 2.5.3
jongo version is 1.2

```java
public class Test {
    private final String value;

    @JsonCreator
    public Test(@JsonProperty("value") String value) {
        this.value = value;
    }
}
```

When deserializing this obejcts of the type Test, an exception is thrown with the following stacktrace

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to org.jongo.marshall.jackson.bson4jackson.MongoBsonGenerator
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2240)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:813)
	at com.fasterxml.jackson.databind.util.TokenBuffer.copyCurrentEvent(TokenBuffer.java:962)
	at com.fasterxml.jackson.databind.util.TokenBuffer.copyCurrentStructure(TokenBuffer.java:1004)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:435)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1443)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1113)
	at org.jongo.marshall.jackson.JacksonEngine.unmarshall(JacksonEngine.java:42)
	... 36 more
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to org.jongo.marshall.jackson.bson4jackson.MongoBsonGenerator
	at org.jongo.marshall.jackson.bson4jackson.BsonSerializers$BsonObjectIdSerializer.serialize(BsonSerializers.java:61)
	at org.jongo.marshall.jackson.bson4jackson.BsonSerializers$BsonObjectIdSerializer.serialize(BsonSerializers.java:58)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	... 47 more
```

The json object being deserialized is the following (the object id is automatically added by mongodb) when the object is saved

```javascript
{ "_id" : { "$oid" : "555e5ea3186b0df9582a51b6"} , "value" : "test"}
```

When I add a private constructor and remove the @JsonCreator annotation the problem is resolved. The problem is also resolved if I add a field _id (or annotated with @MongoId)) or add the @JsonIgnoreProperties("_id") annotation at the class level.

**Comment by MaximeGaudin** [comment]
+1, exactly the same issue when updating Jackson. Did you find anything since May ?

**Comment by haraldrombaut** [comment]
I just added the @JsonIgnoreProperties("_id") annotation to the class, as it seemed the cleanest solution at the time

**Comment by hcapitaine** [comment]
Got the same error but in my case with polymorphism:
```
@JsonTypeInfo(use= JsonTypeInfo.Id.CLASS, property="_class")
public abstract class AbstractCustomer implements Customer {

    private ObjectId _id;
}
```
```
public class Individual extends AbstractCustomer {

    private String lastName;

    private String firstName;
}
```
Any idea how to solve this problem?

**Comment by bguerout** [comment]
Hello,  which version of jackson are you using ?

I can reproduce this exception only with Jackson version greater than 2.6.2.

**Comment by ctrimble** [comment]
Is this also an issue with the current master?  If so, I would be happy to take a look.  1.2 introduced several ID related problems for me and those issues should have been resolved.

**Comment by bguerout** [comment]
Yes this bug is still present in current master.
I was wrong in my previous comment and I was able to reproduce it.
This is due to the fact that we cast JsonGenerator to MongoBsonGenerator in BsonSerializers.
This was "ok" with previous Jongo/Jackson versions but this is no longer possible with Jackson 2.4+.
As far as i understand, this is due to how TokenBuffer handles embedded objects in 2.4+

Here is the test case :
```java
    @Test
    public void canSaveAndMapAPojoWithoutId() throws Exception {

        collection.save(new NoId("test"));

        NoId noId = collection.findOne().as(NoId.class);

        assertThat(noId).isNotNull();
    }

    private static class NoId {
        private final String value;

        @JsonCreator
        public NoId(@JsonProperty("value") String value) {
            this.value = value;
        }
    }
```

**Comment by ctrimble** [comment]
I have a fix working for this specific test case.  I am going to expand the testing and make sure other types will work as well.

**Comment by ctrimble** [comment]
In general, this issue will occur when any field with a type bound in `BsonSerializers` is encountered, but the field is not present in the type specified in the `as(Class<T> type)` clause.  In these cases, Jackson is consuming the tokens with a TokenBuffer and then throwing them away.  The correct fix here seems to be updating `BsonSerializers`, so that a reasonable representation of the type is written to the `JsonGenerator` when it is not of type `MongoBsonGenerator`.  I will finish up my PR and link it to this issue.

**Comment by bguerout** [comment]
Great.

Note that if you upgrade Jackson to 2.6.3+, it seems to use now TokenBuffer to handle polymorphism too (see PolymorphismTest and com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer)

**Comment by bguerout** [comment]
1.3.0 has been released. Fill free to reopen if it still occurs with this new version
